name: Dump firmware (full)

on:
  workflow_dispatch:
    inputs:
      ota:
        description: 'OTA'
        required: true

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install zstd
        curl -L https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz -o - | tar zxf - payload-dumper-go

    - name: Download
      id: download
      run: |
        curl -L ${{ inputs.ota }} -o ota.zip
        unzip -j ota.zip META-INF/com/android/metadata
        echo "ota_ver=`cat metadata | grep ^version_name= | cut -b 14-`" >> "$GITHUB_OUTPUT"
        echo "fingerprint=`cat metadata | grep ^post-build= | cut -b 12-`" >> "$GITHUB_OUTPUT"

    - name: Dump
      run: |
        ./payload-dumper-go -o ota ota.zip > /dev/null
        pushd ota; for f in *; do zstd $f; done; popd

    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: ota/*.img.zst
        artifactErrorsFailBuild: true
        body: |
          ~ Full OTA ~
          Build fingerprint: ${{ steps.download.outputs.fingerprint }}
          OTA URL: ${{ inputs.ota }}
        tag: ${{ steps.download.outputs.ota_ver }}
        token: ${{ secrets.GITHUB_TOKEN }}
